version: '3'
services:

  maxbase-portal-admin-v2:
    container_name: maxbase-portal-admin-v2
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: harborIp/maxcloud/maxbase-portal-admin-v2:theversion
    privileged: true
    ports:
      - 10019:10019
    volumes:
      - /opt/logs/maxbase-portal-admin-v2:/opt/logs/maxbase-portal-admin-v2
      - /opt/portal-v2-img:/app/img
    environment:
      - SQL_ENV_NAME=dev
      - SHOW_VERIFY_CODE=true
      - EUREKA_HOST=theeurekaip
      - EUREKA_PORT=8761
      - IP_ADDRESS=theip
      - MASTER_MYSQL_HOST=theip
      - MASTER_MYSQL_PORT=3306
      - MASTER_MYSQL_USERNAME=root
      - MASTER_MYSQL_PASSWORD=Foxconn123
      - SLAVE_MYSQL_HOST=theip
      - SLAVE_MYSQL_PORT=3306
      - SLAVE_MYSQL_USERNAME=root
      - SLAVE_MYSQL_PASSWORD=Foxconn123
      - LOG_PATH=/opt/logs/maxbase-portal-admin-v2
      - LOG_FILE=maxbase-storage
      - LOG_MAX_FILE_SIZE=100MB
      - LOG_MAX_HISTORY_DAYS=30
      - LOG_ROOT_LEVEL=info
      - FILE_RANDOM_PATH=/app/img/random/
      - FILE_ASSIGNATION_PATH=/app/img/assignation/
      - DB_AUTO_INIT=thedbinit
      - TZ=Asia/Shanghai

networks:
  default:
    external:
      name: maxcloud
