version: '3'
services:

  maxbase-portal-ms-web-v2:
    container_name: maxbase-portal-ms-web-v2
    image: harborIp/maxcloud/maxbase-portal-ms-web-v2:theversion
    privileged: true
    ports:
      - 706:443
    volumes:
      - /opt/maxcloud/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=Asia/Shanghai

networks:
  default:
    external:
      name: maxcloud
